# Generated by Django 4.2.4 on 2024-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_cliente_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='produit',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='sale_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
