# Generated by Django 4.2.4 on 2024-12-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_categories_options_produit_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categories'),
        ),
    ]
